version: '3.7'

services:
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
            target: php-xdebug
        volumes:
            - .:/var/www
            - ./docker/.composer/cache:/.composer/cache/
        environment:
            - xdebug.mode=debug